apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.delegateLabels }}
      {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.delegateLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.delegateAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
      {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.delegateAnnotations }}
      {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.delegateAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  name: {{ include "harness-delegate-ng.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      {{- include "harness-delegate-ng.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.deploymentStrategy | default "RollingUpdate" }}
    {{- if eq (.Values.deploymentStrategy | default "RollingUpdate") "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable | default 1 }}
    {{- end }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
        checksum/secret: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum | trunc 63 }}
        checksum/configmap: {{ include (print .Template.BasePath "/configMap.yaml") . | sha256sum | trunc 63 }}
        {{- if .Values.commonAnnotations }}
          {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.delegateAnnotations }}
          {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.delegateAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
      labels:
        {{- include "harness-delegate-ng.selectorLabels" . | nindent 8 }}
        {{- if .Values.commonLabels }}
          {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.delegateLabels }}
          {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.delegateLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.delegatePodLabels }}
          {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.delegatePodLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "harness-delegate-ng.serviceAccountName" . }}
      terminationGracePeriodSeconds: 600
      restartPolicy: Always
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      securityContext:
        fsGroup: 1001
      {{- if .Values.custom_init_containers }}
      initContainers:
        {{- toYaml .Values.custom_init_containers | nindent 8 }}
      {{- end }}
      containers:
        - name: delegate
          {{- if and .Values.image.registry .Values.image.repository}}
          image: "{{ $.Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- else if .Values.image.repository }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: {{ .Values.delegateDockerImage }}
          {{- end }}
          {{- if .Values.securityContext.runAsRoot }}
          securityContext:
            {{- toYaml .Values.delegateSecurityContext | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
            - name: api
              containerPort: 3460
          resources:
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- else }}
            limits:
              memory: {{ include "harness-delegate-ng.assignedMemory" .}}
            requests:
              cpu: {{ .Values.cpu }}
              memory: {{ include "harness-delegate-ng.assignedMemory" .}}
            {{- end }}
          startupProbe:
            httpGet:
              path: /api/health
              port: 3460
              scheme: HTTP
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds:  {{ .Values.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3460
              scheme: HTTP
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          envFrom:
            - configMapRef:
                name: {{ template "harness-delegate-ng.fullname" . }}
            - secretRef:
                name: {{ include "harness-delegate-ng.delegateToken" . }}
            - configMapRef:
                name: {{ template "harness-delegate-ng.fullname" . }}-proxy
                optional: true
            - secretRef:
                name: {{ template "harness-delegate-ng.fullname" . }}-proxy
                optional: true
            - configMapRef:
                name: {{ template "harness-delegate-ng.fullname" . }}-shared-certificates
                optional: true
          {{- with .Values.custom_envs }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if $.Values.shared_certificates.ca_bundle }}
            - name: certvol
              mountPath: {{ .Values.shared_certificates.certs_path }}
              subPath:  ca.bundle
          {{- end }}
          {{- if $.Values.delegateCustomCa.secretName }}
            - name: custom-certs
              mountPath: /opt/harness-delegate/ca-bundle/
              readOnly: true
          {{- end }}
          {{- if .Values.mTLS.secretName }}
            - name: client-certificate
              mountPath: /etc/mtls
              readOnly: true
          {{- end }}
          {{- with .Values.custom_mounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.custom_containers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if $.Values.shared_certificates.ca_bundle }}
        - name: certvol
          secret:
            secretName: {{ template "harness-delegate-ng.fullname" . }}-addcerts
            items:
            - key: ca.bundle
              path: ca.bundle
      {{- end }}
      {{- if $.Values.delegateCustomCa.secretName }}
        - name: custom-certs
          secret:
            secretName: {{ .Values.delegateCustomCa.secretName }}
            defaultMode: 400
      {{- end }}
      {{- if .Values.mTLS.secretName }}
        - name: client-certificate
          secret:
            secretName: {{ .Values.mTLS.secretName }}
            defaultMode: 400
      {{- end }}
      {{- with .Values.custom_volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
