{{- if .Values.upgrader.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "harness-delegate-ng.fullname" . }}-upgrader-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    mode: Delegate
    dryRun: false
    workloadName: {{ template "harness-delegate-ng.fullname" . }}
    namespace: {{ .Release.Namespace }}
    containerName: delegate
    {{- if .Values.mTLS.secretName }}
    clientCertificateFilePath: "/etc/mtls/client.crt"
    clientCertificateKeyFilePath: "/etc/mtls/client.key"
    {{- end }}
    {{- if .Values.upgrader.registryMirror }}
    registryMirror: {{ .Values.upgrader.registryMirror }}
    {{- end }}
    delegateConfig:
      accountId: {{ .Values.accountId }}
      managerHost: {{ .Values.managerEndpoint }}
    proxyScheme: {{ .Values.proxyScheme }}
    proxyHost: {{ .Values.proxyHost }}
    proxyPort: {{ .Values.proxyPort }}
    {{- if .Values.proxyUser }}
    proxyUser: {{ .Values.proxyUser | b64dec}}
    proxyPassword: {{ .Values.proxyPassword | b64dec }}
    {{- end }}
{{- end }}
